// Missao 5/livro-servidor/clientes/livros-react/src/LivroLista.js
import React, { useState, useEffect } from 'react';
import { ControleLivro } from './controle/ControleLivro';
import { ControleEditora } from './controle/ControleEditora';
import './LivroLista.css';

const LinhaLivro = ({ livro, excluir }) => {
    const controleEditora = new ControleEditora();
    const nomeEditora = controleEditora.getNomeEditora(livro.codEditora);

    return (
        <tr>
            <td>
                <div>{livro.titulo}</div>
                <button onClick={() => excluir(livro.codigo)}>Excluir</button>
            </td>
            <td>{livro.resumo}</td>
            <td>{nomeEditora}</td>
            <td>{livro.autores.join(", ")}</td>
        </tr>
    );
};

const LivroLista = () => {
    const [livros, setLivros] = useState([]);
    const [carregado, setCarregado] = useState(false);
    const ControleLivros = new ControleLivro();

    useEffect(() => {
        if (!carregado) {
            ControleLivros.obterTodos()
                .then(result => {
                    setLivros(result);
                    setCarregado(true);
                })
                .catch(error => {
                    console.error('Erro ao obter livros:', error);
                });
        }
    }, [carregado]);

    const excluir = codigo => {
        ControleLivros.excluir(codigo)
            .then(() => {
                setCarregado(false);
            })
            .catch(error => {
                console.error('Erro ao excluir livro:', error);
            });
    };

    return (
        <main>
            <h1>Catálogo de Livros</h1>
            <table>
                <thead>
                    <tr>
                        <th>Título</th>
                        <th>Resumo</th>
                        <th>Editora</th>
                        <th>Autores</th>
                    </tr>
                </thead>
                <tbody>
                    {livros.map((livro, index) => (
                        <LinhaLivro key={index} livro={livro} excluir={excluir} />
                    ))}
                </tbody>
            </table>
        </main>
    );
};

export default LivroLista;

// Missão 4/livros-angular/src/app/livro-lista/livro-lista.component.ts
import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { Livro } from '../livro';
import { ControleEditoraService } from '../controle-editora.service';
import { ControleLivrosService } from '../controle-livros.service';

@Component({
  selector: 'app-livro-lista',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './livro-lista.component.html',
  styleUrls: ['./livro-lista.component.css']
})
export class LivroListaComponent implements OnInit {
  public livros: Livro[] = [];

  constructor(
    private servEditora: ControleEditoraService,
    private servLivros: ControleLivrosService
  ) { }

  ngOnInit() {
    this.carregarLivros();
  }

  carregarLivros() {
    this.livros = this.servLivros.obterLivros();
  }

  excluir(codigo: number) {
    this.servLivros.excluir(codigo);
    this.carregarLivros(); 
  }

  obterNomeEditora(codEditora: number): string | undefined {
    return this.servEditora.getNomeEditora(codEditora);
  }
}

<main class="container">
  <h1>Catálogo de Livros</h1>
  <table class="table">
    <thead>
      <tr>
        <th>Título</th>
        <th>Resumo</th>
        <th>Editora</th>
        <th>Autores</th>
        <th>Ações</th>
      </tr>
    </thead>
    <tbody>
      <tr *ngFor="let livro of livros">
        <td>
          {{ livro.titulo }}
          <button class="btn btn-danger btn-sm" (click)="excluir(livro.codigo)">Excluir</button>
        </td>
        <td>{{ livro.resumo }}</td>
        <td>{{ obterNomeEditora(livro.codEditora) }}</td>
        <td>
          <ul>
            <li *ngFor="let autor of livro.autores">
              {{ autor }}
            </li>
          </ul>
        </td>
        <td>
        </td>
      </tr>
    </tbody>
  </table>
</main>
